version: "3.3"
services:
  postgres-prod:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_PASSWORD: ${TRA_PROD_PG_PASSWORD:-password}
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app-prod:
    build:
      context: .
      dockerfile: ./docker/prod/app.Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    environment:
      TRA_PROD_USER_PASSWORD: ${TRA_PROD_USER_PASSWORD:-password}
    volumes:
      - .:/app
    depends_on:
      - postgres-prod
  nginx-prod:
    build:
      context: .
      dockerfile: ./docker/prod/nginx.Dockerfile
    depends_on:
      - app-prod
    ports:
      - ${TRA_PROD_NGINX_HOST_PORT:-80}:80
volumes:
  pg-prod-data:
